# Register
POST http://localhost:8000/api/auth/register
Accept: application/json
Content-Type: application/json

{
  "username": "test",
  "password": "123"
}

###

# Login
POST http://localhost:8000/api/auth/login
Accept: application/json
Content-Type: application/json

{
  "username": "test",
  "password": "123"
}

###

# Auth
POST http://localhost:8000/api/auth/
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInVzZXJuYW1lIjoidGVzdCIsImlhdCI6MTcxOTk1MjgyOSwiZXhwIjoxNzIwMDM5MjI5fQ.-1qUo-8-4oj-oDRUKzmyFgoZ94M2dbQJ8adg-qkCJnU
Content-Type: application/json


###

# Advanced Search
GET http://localhost:8000/api/titles/advancedsearch?sort=oldest&maxYear=2022
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInVzZXJuYW1lIjoidGVzdCIsImlhdCI6MTcxOTg2MzI2OCwiZXhwIjoxNzE5OTQ5NjY4fQ.6yoJ17mwfNDZ8hTwc7MNFTVQNBQ3DjI7hdDFY3coMx4

###

# Activites
GET http://localhost:8000/api/activity
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInVzZXJuYW1lIjoidGVzdCIsImlhdCI6MTcyMDQ2MDAwMywiZXhwIjoxNzIwNTQ2NDAzfQ.TVD6sE8vsGEAlvzZwxDU7NkaR03j0VxZ-LiTXnHnh4A
